/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEventToFilmDialog: typeof import('./src/components/film-collection/AddEventToFilmDialog.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    CreateEventDialog: typeof import('./src/components/film-collection/CreateEventDialog.vue')['default']
    CreateFilmDialog: typeof import('./src/components/film-collection/CreateFilmDialog.vue')['default']
    EditEventDialog: typeof import('./src/components/film-collection/EditEventDialog.vue')['default']
    EditFilmDialog: typeof import('./src/components/film-collection/EditFilmDialog.vue')['default']
    EventLogTable: typeof import('./src/components/film-collection/EventLogTable.vue')['default']
    FilmCollection: typeof import('./src/components/film-collection/FilmCollection.vue')['default']
    FilmCollectionTable: typeof import('./src/components/film-collection/FilmCollectionTable.vue')['default']
    FilmEventLogTable: typeof import('./src/components/film-collection/FilmEventLogTable.vue')['default']
    FilmForm: typeof import('./src/components/film-collection/FilmForm.vue')['default']
    UniqueFilmsTable: typeof import('./src/components/film-collection/UniqueFilmsTable.vue')['default']
  }
}
