/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth.vue')['default']
    CreateFilmDialog: typeof import('./src/components/CreateFilmDialog.vue')['default']
    Database: typeof import('./src/components/database.vue')['default']
    EditFilmDialog: typeof import('./src/components/EditFilmDialog.vue')['default']
    EventLogDialog: typeof import('./src/components/EventLogDialog.vue')['default']
    EventLogDualog: typeof import('./src/components/EventLogDualog.vue')['default']
    FilmCollection: typeof import('./src/components/FilmCollection.vue')['default']
    FilmCollectionTable: typeof import('./src/components/FilmCollectionTable.vue')['default']
    FilmForm: typeof import('./src/components/FilmForm.vue')['default']
  }
}
