/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth.vue')['default']
    CreateFilmDialog: typeof import('./src/components/film-collection/CreateFilmDialog.vue')['default']
    EditFilmDialog: typeof import('./src/components/film-collection/EditFilmDialog.vue')['default']
    EventLog: typeof import('./src/components/EventLog.vue')['default']
    EventLogDialog: typeof import('./src/components/EventLogDialog.vue')['default']
    EventLogTable: typeof import('./src/components/film-collection/EventLogTable.vue')['default']
    FilmCollection: typeof import('./src/components/film-collection/FilmCollection.vue')['default']
    FilmCollectionTable: typeof import('./src/components/film-collection/FilmCollectionTable.vue')['default']
    FilmForm: typeof import('./src/components/film-collection/FilmForm.vue')['default']
  }
}
